### ISSUE TITLE
DB error on boot

### ISSUE THREAD

**Issue by oytuntez** [tokenmill/accelerated-text#335]
When we restart our server, we started to receive this error on API container:

```


Execution error (ExceptionInfo) at datomic.peer.Connection/fn (peer.clj:241).
--
org.h2.jdbc.JdbcSQLException: General error: "java.lang.ArrayIndexOutOfBoundsException: 0"; SQL statement:
select id, rev, map, val from datomic_kvs where id = ? [50000-171]
Full report at:
/tmp/clojure-7933084181292962952.edn


```

Any ideas?

**Comment by oytuntez** [comment]
And some logs from datomic container:

```
2021-08-04 10:36:22.072 INFO  default    datomic.kv-sql - {:event :kv-sql/put-failed, :id "ref-index-root/acc-text-b6eb9db0-328a-41f8-a32b-0d6310f75fdb", :desc "Unique index or primary key violation: \"PRIMARY_KEY_B ON PUBLIC.DATOMIC_KVS(ID)\"; SQL statement:\ninsert into datomic_kvs (id, rev, map) values (?, ?, ?) [23505-171]", :pid 1, :tid 46}
```

```
2021-08-04 10:36:32.652 INFO  default    datomic.update - {:event :transactor/admin-command, :cmd :start-database, :arg "acc-text-b6eb9db0-328a-41f8-a32b-0d6310f75fdb", :result {:version "0.9.5703.21", :peers 2, :type :free, :failed "org.h2.jdbc.JdbcSQLException: General error: \"java.lang.ArrayIndexOutOfBoundsException: 0\"; SQL statement:\nselect id, rev, map, val from datomic_kvs where id = ? [50000-171]"}, :pid 1, :tid 43}

2021-08-04 10:36:32.672 WARN  default    datomic.update - {:message "Start database failed", :pid 1, :tid 21}
java.util.concurrent.ExecutionException: org.h2.jdbc.JdbcSQLException: General error: "java.lang.ArrayIndexOutOfBoundsException: 0"; SQL statement:
select id, rev, map, val from datomic_kvs where id = ? [50000-171]
at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_232]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_232]
at clojure.core$deref_future.invokeStatic(core.clj:2300) ~[clojure-1.10.0.jar:na]
at clojure.core$future_call$reify__8439.deref(core.clj:6974) ~[clojure-1.10.0.jar:na]
at clojure.core$deref.invokeStatic(core.clj:2320) ~[clojure-1.10.0.jar:na]
at clojure.core$deref.invoke(core.clj:2306) ~[clojure-1.10.0.jar:na]
at datomic.index$init_index.invokeStatic(index.clj:752) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.index$init_index.invoke(index.clj:748) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.log$ensure_index_and_log$fn__8670.invoke(log.clj:649) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.log$ensure_index_and_log.invokeStatic(log.clj:645) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.log$ensure_index_and_log.invoke(log.clj:641) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.update.Master$fn__12096.invoke(update.clj:548) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.update.Master.internal_start_database(update.clj:532) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at datomic.update.Master$fn__12102.invoke(update.clj:653) ~[datomic-transactor-free-0.9.5703.21.jar:na]
at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030) [clojure-1.10.0.jar:na]
at clojure.lang.AFn.call(AFn.java:18) [clojure-1.10.0.jar:na]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_232]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_232]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_232]


```

**Comment by rokasramas** [comment]
if you have a backup of your document plans, try deleting datomic volume (needed steps are listed here: https://accelerated-text.readthedocs.io/en/latest/troubleshooting/).
